#!/usr/bin/env node
/*
 * SlabSense — https://www.slabsenseai.com
 * Copyright (c) 2026 SlabSense. All rights reserved.
 * Proprietary and confidential; see LICENSE at the repository root.
 */
/**
 * Writes NOTICE.md: every direct npm dependency with its licence (read from node_modules), plus
 * the non-npm third-party material the product ships or relies on. Run after changing
 * package.json: `node scripts/legal/build-notice.mjs` (audit H-01, H-17).
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const rows = [];
for (const [section, deps] of [['Runtime (shipped to users or run on our servers)', pkg.dependencies || {}], ['Development and tooling only', pkg.devDependencies || {}]]) {
  const list = [];
  for (const name of Object.keys(deps).sort()) {
    try {
      const p = JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules', name, 'package.json'), 'utf8'));
      const lic = typeof p.license === 'string' ? p.license : p.license?.type || (Array.isArray(p.licenses) ? p.licenses.map((l) => l.type).join(' / ') : 'unknown');
      const url = p.homepage || (typeof p.repository === 'string' ? p.repository : p.repository?.url) || '';
      list.push(`| ${name} | ${p.version} | ${lic} | ${url.replace(/^git\+/, '').replace(/\.git$/, '')} |`);
    } catch {
      list.push(`| ${name} | ${deps[name]} | (not installed) | |`);
    }
  }
  rows.push(`### ${section}\n\n| Package | Version | Licence | Source |\n|---|---|---|---|\n${list.join('\n')}`);
}

const extra = `
### Fonts (bundled in \`public/fonts\`)

| Font | Licence | Source |
|---|---|---|
| Inter (Latin subset, variable) | SIL Open Font License 1.1 | https://github.com/rsms/inter |
| JetBrains Mono (Latin subset, variable) | SIL Open Font License 1.1 | https://github.com/JetBrains/JetBrainsMono |

### Models and weights

| Component | Licence | Notes |
|---|---|---|
| ConvNeXt-Tiny and MobileNetV3 ImageNet-pretrained weights (timm) | Apache-2.0 | fine-tuned into the SlabSense corner, edge, card and centering models (\`training/\`) |
| CLIP ViT-B/32 (\`Xenova/clip-vit-base-patch32\`, ONNX export of OpenAI CLIP) | MIT | card identification embeddings, run in the browser |
| ONNX Runtime Web | MIT | runs the on-device models (copy served from our models bucket) |
| Tesseract.js / tessdata | Apache-2.0 | set-number OCR for identification |

### Services and data

| Provider | Role | Terms |
|---|---|---|
| Anthropic (Claude) | paid AI Grade inspection | Anthropic Commercial Terms |
| Supabase | authentication, database, storage | Supabase Terms of Service |
| Vercel | hosting and serverless API | Vercel Terms of Service |
| Stripe | web payments and slab orders | Stripe Services Agreement |
| Apple App Store | in-app purchase (iOS app); Apple Root CA certificates bundled in \`api/_lib/apple-roots/\` for receipt verification | Apple Developer Program License Agreement |
| TCGdex | card names, sets and reference images for identification | TCGdex API terms; card artwork remains the property of its owners |
| Cardmarket (via TCGdex) | market values shown in the collection | attribution shown in-app |

Grading-company names (PSA, BGS, CGC, SGC, TAG) are trademarks of their respective owners, used only to
identify the published scale an estimate is compared against. SlabSense is not affiliated with any of them.
`;

const out = `# Third-party notices

Generated by \`scripts/legal/build-notice.mjs\` on ${new Date().toISOString().slice(0, 10)}. SlabSense itself is proprietary (see LICENSE); the components below are used under their own licences.

${rows.join('\n\n')}
${extra}`;
fs.writeFileSync(path.join(ROOT, 'NOTICE.md'), out);
console.log('wrote NOTICE.md');
