/**
 * SlabSense - Export Card
 * Generates shareable grade result image
 */

import { useRef, useState } from 'react';

const mono = "'JetBrains Mono','SF Mono',monospace";
const sans = "'Inter',-apple-system,sans-serif";

export function ExportCard({ gradeResult, frontImage, backImage, gradingCompany, onClose }) {
  const cardRef = useRef(null);
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  const gr = gradeResult;
  if (!gr) return null;

  const companyLabels = {
    tag: 'TAG',
    psa: 'PSA',
    bgs: 'BGS',
    cgc: 'CGC',
    sgc: 'SGC',
  };

  const getGradeColor = (grade) => {
    if (grade >= 9.5) return '#00ff88';
    if (grade >= 9) return '#66dd44';
    if (grade >= 8) return '#ffcc00';
    if (grade >= 7) return '#ff9944';
    return '#ff6633';
  };

  const gradeColor = getGradeColor(gr.grade.grade);

  // Export as PNG using canvas
  const handleExportImage = async () => {
    setExporting(true);
    try {
      const card = cardRef.current;
      if (!card) return;

      // Use html2canvas dynamically
      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(card, {
        backgroundColor: '#0a0b0e',
        scale: 2,
      });

      // Download
      const link = document.createElement('a');
      link.download = `slabsense-grade-${gr.grade.grade}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (err) {
      console.error('Export failed:', err);
      alert('Export failed. Try again.');
    } finally {
      setExporting(false);
    }
  };

  // Copy text summary to clipboard
  const handleCopyText = async () => {
    const text = `SlabSense Grade Report
━━━━━━━━━━━━━━━━━━━━
${companyLabels[gradingCompany]} Estimate: ${gr.grade.grade} (${gr.grade.label})
Raw Score: ${gr.rawScore}/1000
DINGS: ${gr.totalDings}

Subgrades:
• Front Center: ${gr.subgrades.frontCenter}/1000
• Back Center: ${gr.subgrades.backCenter}/1000
• Corners: ${gr.subgrades.corners}/1000
• Edges: ${gr.subgrades.edges}/1000
• Surface: ${gr.subgrades.surface}/1000

Generated by SlabSense
slabsense.vercel.app`;

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Copy failed:', err);
    }
  };

  return (
    <div style={{
      position: 'fixed',
      inset: 0,
      background: 'rgba(0,0,0,0.9)',
      zIndex: 1000,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
    }}>
      {/* Close button */}
      <button
        onClick={onClose}
        style={{
          position: 'absolute',
          top: 16,
          right: 16,
          background: 'transparent',
          border: 'none',
          color: '#666',
          fontSize: 24,
          cursor: 'pointer',
        }}
      >
        ×
      </button>

      {/* Exportable Card */}
      <div
        ref={cardRef}
        style={{
          background: '#0a0b0e',
          borderRadius: 16,
          border: `2px solid ${gradeColor}44`,
          padding: 20,
          maxWidth: 340,
          width: '100%',
        }}
      >
        {/* Header */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: 16,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <div style={{
              width: 28,
              height: 28,
              borderRadius: 6,
              background: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontFamily: mono,
              fontWeight: 900,
              fontSize: 10,
              color: '#fff',
            }}>
              SS
            </div>
            <span style={{ fontFamily: mono, fontSize: 12, color: '#555' }}>SlabSense</span>
          </div>
          <div style={{
            padding: '4px 10px',
            borderRadius: 4,
            background: `${gradeColor}22`,
            fontFamily: mono,
            fontSize: 10,
            color: gradeColor,
            textTransform: 'uppercase',
          }}>
            {companyLabels[gradingCompany]} Estimate
          </div>
        </div>

        {/* Card Images */}
        <div style={{ display: 'flex', gap: 10, marginBottom: 16 }}>
          <div style={{ flex: 1, aspectRatio: '2.5/3.5', borderRadius: 8, overflow: 'hidden', background: '#151720' }}>
            {frontImage && <img src={frontImage} style={{ width: '100%', height: '100%', objectFit: 'contain' }} />}
          </div>
          <div style={{ flex: 1, aspectRatio: '2.5/3.5', borderRadius: 8, overflow: 'hidden', background: '#151720' }}>
            {backImage && <img src={backImage} style={{ width: '100%', height: '100%', objectFit: 'contain' }} />}
          </div>
        </div>

        {/* Grade Display */}
        <div style={{
          textAlign: 'center',
          padding: 16,
          background: `${gradeColor}11`,
          borderRadius: 12,
          border: `1px solid ${gradeColor}33`,
          marginBottom: 16,
        }}>
          <div style={{ fontFamily: mono, fontSize: 48, fontWeight: 900, color: gradeColor }}>
            {gr.grade.grade}
          </div>
          <div style={{ fontFamily: mono, fontSize: 14, fontWeight: 600, color: gradeColor, marginTop: 4 }}>
            {gr.grade.label}
          </div>
          <div style={{ fontFamily: mono, fontSize: 11, color: '#555', marginTop: 8 }}>
            Raw Score: {gr.rawScore}/1000 · {gr.totalDings} DING{gr.totalDings !== 1 ? 'S' : ''}
          </div>
        </div>

        {/* Subgrades */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: 8,
          marginBottom: 12,
        }}>
          {[
            { label: 'Center F', value: gr.subgrades.frontCenter },
            { label: 'Center B', value: gr.subgrades.backCenter },
            { label: 'Corners', value: gr.subgrades.corners },
            { label: 'Edges', value: gr.subgrades.edges },
            { label: 'Surface', value: gr.subgrades.surface },
            { label: 'DINGS', value: gr.totalDings, isDing: true },
          ].map((sg, i) => (
            <div key={i} style={{
              padding: '8px 6px',
              background: '#0d0f13',
              borderRadius: 6,
              textAlign: 'center',
            }}>
              <div style={{ fontFamily: mono, fontSize: 8, color: '#555', marginBottom: 4, textTransform: 'uppercase' }}>
                {sg.label}
              </div>
              <div style={{
                fontFamily: mono,
                fontSize: 14,
                fontWeight: 700,
                color: sg.isDing
                  ? (sg.value === 0 ? '#00ff88' : sg.value <= 2 ? '#ffcc00' : '#ff6633')
                  : (sg.value >= 950 ? '#00ff88' : sg.value >= 900 ? '#66dd44' : sg.value >= 800 ? '#ffcc00' : '#ff6633'),
              }}>
                {sg.isDing ? sg.value : sg.value}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div style={{
          textAlign: 'center',
          fontFamily: mono,
          fontSize: 9,
          color: '#333',
          paddingTop: 8,
          borderTop: '1px solid #1a1c22',
        }}>
          Not affiliated with any grading company · Estimate only
        </div>
      </div>

      {/* Action Buttons */}
      <div style={{ display: 'flex', gap: 12, marginTop: 20 }}>
        <button
          onClick={handleExportImage}
          disabled={exporting}
          style={{
            padding: '12px 24px',
            borderRadius: 8,
            border: 'none',
            background: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
            color: '#fff',
            fontFamily: mono,
            fontSize: 12,
            fontWeight: 600,
            cursor: exporting ? 'wait' : 'pointer',
            textTransform: 'uppercase',
          }}
        >
          {exporting ? 'Exporting...' : 'Download PNG'}
        </button>
        <button
          onClick={handleCopyText}
          style={{
            padding: '12px 24px',
            borderRadius: 8,
            border: '1px solid #2a2d35',
            background: copied ? 'rgba(0,255,136,0.1)' : 'transparent',
            color: copied ? '#00ff88' : '#888',
            fontFamily: mono,
            fontSize: 12,
            fontWeight: 600,
            cursor: 'pointer',
            textTransform: 'uppercase',
          }}
        >
          {copied ? 'Copied!' : 'Copy Text'}
        </button>
      </div>
    </div>
  );
}
